"use client";
import { FormEvent, useEffect, useState } from "react";
import { browserSupabase } from "@/lib/supabase";

const supabase=browserSupabase();
type Registration={id:string;category:string;province:string;district:string;verification:string;profile:{full_name:string;phone:string;photo_url:string};documents:{id:string;kind:string;status:string;url?:string|null;storage_error?:string|null;file_name?:string}[]};
function DocumentLink({doc}:{doc:Registration["documents"][number]}){const image=/\.(jpe?g|png|webp|gif)$/i.test(doc.file_name??"")||doc.kind.startsWith("bi_");if(!doc.url)return <span className="doc-error" title={doc.storage_error??"URL temporária indisponível"}>{doc.kind} · indisponível</span>;return <a className="doc-item" target="_blank" rel="noreferrer" href={doc.url}>{image?<img className="doc-preview" src={doc.url} alt={`Pré-visualização ${doc.kind}`}/>:<span className="doc-file">PDF</span>}<span>{doc.kind} ↗</span></a>};
async function call(url:string,init:RequestInit={}){const {data:{session}}=await supabase.auth.getSession();return fetch(url,{...init,headers:{...init.headers,Authorization:`Bearer ${session?.access_token??""}`}});}

export default function Admin(){const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[rows,setRows]=useState<Registration[]>([]),[isAdmin,setIsAdmin]=useState(false),[checked,setChecked]=useState(false);const load=async()=>{const r=await call("/api/admin/registrations");const j=await r.json();setChecked(true);if(!r.ok){setIsAdmin(false);setError(j.error??"");return;}setIsAdmin(true);setError("");setRows(j.registrations??[]);};useEffect(()=>{void load();},[]);async function login(e:FormEvent){e.preventDefault();const r=await supabase.auth.signInWithPassword({email,password});if(r.error){setError(r.error.message);return;}void load();}async function review(id:string,status:"approved"|"rejected"){const r=await call("/api/admin/registrations",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});if(!r.ok)setError((await r.json()).error);else void load();}
 if(!checked||!isAdmin)return <main className="admin"><section><p>ADMINISTRAÇÃO BISCATEMZ</p><h1>Entrar no painel</h1><form onSubmit={login}><input type="email" placeholder="E-mail administrativo" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Palavra-passe" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary">Entrar</button></form>{error&&<small>{error}</small>}<em>Crie a sua conta primeiro no site e promova-a a administrador uma única vez no SQL Editor, conforme o README.</em></section></main>;
 return <main className="admin"><header><a className="brand" href="/">BiscaTe<span>MZ</span></a><button onClick={()=>void load()}>Atualizar</button></header><section><p>PAINEL PRIVADO</p><h1>Cadastros de prestadores</h1>{error&&<small>{error}</small>}{rows.length===0&&<p>Nenhum cadastro pendente ou analisado.</p>}{rows.map(row=><article className="admin-card" key={row.id}><img src={row.profile.photo_url||"/avatar.svg"} alt=""/><div><h2>{row.profile.full_name}</h2><p>{row.category} · {row.district}, {row.province}<br/>{row.profile.phone}</p><b>{row.verification}</b><div className="docs">{row.documents.map(d=><DocumentLink key={d.id} doc={d}/>)}</div></div>{row.verification==="pending"&&<footer><button onClick={()=>void review(row.id,"rejected")}>Recusar</button><button className="primary" onClick={()=>void review(row.id,"approved")}>Aprovar</button></footer>}</article>)}</section></main>;
}
